### ISSUE TITLE
Logo Addition/Correction

### ISSUE THREAD

**Issue by tpolise1** [medhacks/SplashPage2k16#14]
1) Increase size of JH Career Center and JH School of Medicine logo in Partners to make it more proportionate to the others
2) Add the TMC logo under Sponsors, specifically next to Thiel Fellowship logo (their request)
3) Add JH Alumni logo under Partners

**Comment by eburnette1** [comment]
Done -- the career center logo can't be bigger if you want it to be on the same line as the SOM
