### ISSUE TITLE
Logo Sizes +Schedule

### ISSUE THREAD

**Issue by tpolise1** [medhacks/SplashPage2k16#3]
For sponsors, make all logos same size EXCEPT JHU Medicine is larger and top.
For partners, make School of Nursing a little bigger (looks smaller compared to others).

Also change Team Registration to 9:15 pm (NOT 10:15 pm)..

**Comment by errcHuang** [comment]
We could organize our sponsors this way as well. Like most prominent sponsors at top. 

http://www.calhacks.io/ <--- example

github repo for calhacks -- https://github.com/calhacks/website2

**Comment by vicmart** [comment]
If you can give me a list of sponsors in order of which are more important I can organize them like calhacks
