### ISSUE TITLE
Add API link

### ISSUE THREAD

**Issue by tpolise1** [medhacks/SplashPage2k16#32]
Add API link
https://drive.google.com/drive/folders/0ByylvYVnMCtXRHlKMlFsN0hEajg?usp=sharing
to Links under Information

**Comment by eburnette1** [comment]
<img width="1278" alt="screen shot 2016-09-23 at 14 20 20" src="https://cloud.githubusercontent.com/assets/7110499/18796796/e44146c8-8198-11e6-879d-9f4bfb9469b5.png">
pretty sure this won't do anything if I can't even access it
