### ISSUE TITLE
Update schedule

### ISSUE THREAD

**Issue by errcHuang** [medhacks/SplashPage2k16#33]
SCHEDULE OVERVIEW
Friday - September 23rd, 2016 
5:00pm-6:00p        Registration                2nd floor
5:00pm-6:30pm       Sponsor Fair                2nd floor
5:30pm-6:30pm       Dinner                  2nd floor 
6:30pm-7:30pm       Opening Ceremony            Auditorium (272)  
7:45pm-8:45pm       Problem/Solution Pitching Session   3rd floor & 464 & 472
8:45pm-10:30pm  Team Formation / Solution Discussion    3rd floor & 464 & 472
9:00pm-9:30pm       BD presents -               278
Forging a career in the Biotech Industry
9:00am-9:30pm       Redox presents -            274
            Integrating health data across platforms
9:15pm          Team Registration Begins        3rd floor
9:30pm          Hacking Begins              All of Bloomberg
11:45pm-12:45am MLH presents -              274
            Slideshare Karaoke
Saturday - September 24th, 2016 
12:00am     Midnight Snack              2nd floor
8:30am          Breakfast               2nd floor
10:30am     Morning Snack               2nd floor
12:00pm     Lunch                   2nd floor
2:00pm-3:00pm       Johnson & Johnson presents -        274
            Innovation in Healthcare
3:00pm          Afternoon Snack         2nd floor
3:00pm-3:45pm       Intro to Apache Spark Workshop -    276
            Open-Source Machine Learning  
6:30pm          Dinner                  2nd floor
6:30pm          Team Registration Due           2nd floor
8:00pm-9:00pm       MLH presents -              274
            Cybersecurity Capture-the-Flag

Sunday - September 25th, 2016 
12:00am     Midnight Snack              2nd floor
8:30am-9:30am       Breakfast               2nd floor
9:30am          Submissions due on Devpost      Everywhere
10:00am-10:30am TMC presents -          274
            Structuring a Potent Pitch
11:00am-1:00pm  Preliminary Judging Round       4th floor
1:00pm          Lunch  
1:00pm-2:00pm       Networking with Judges/Mentors  2nd floor
2:00pm-3:00pm       Finalist Presentations          Auditorium (272)
3:30pm-4:00pm       Awards + Closing Remarks        Auditorium (272)

**Comment by eburnette1** [comment]
are you sure you mean room 472 for the pitches? I thought we were using 478? @errcHuang

**Comment by errcHuang** [comment]
oh shit you're right 478 myb

On Thu, Sep 22, 2016 11:01 PM, emily burnette notifications@github.com
wrote:
are you sure you mean room 472 for the pitches? I thought we were using 478? 
@errcHuang
