### ISSUE TITLE
Make repo private

### ISSUE THREAD

**Issue by ryerrabelli** [medhacks/SplashPage2k16#36]
Victor, please make repo private as we discussed.

**Comment by vicmart** [comment]
@ronnyb29 can you do this? I'm not able to without upgrading...

**Comment by ryerrabelli** [comment]
Victor, is it possible that this is because you ran out of private repositories? I have unlimited because of this https://education.github.com/pack

**Comment by ronboger** [comment]
@ryerrabelli @Vicmart1 it's on the MedHacks repo, so if we want to make it private we'll need to pay as an organization

**Comment by ronboger** [comment]
there may be ways we can get it free through github education?

**Comment by ryerrabelli** [comment]
Oh I see the problem.  Did you get the MedHacks organization repo from the "Use GitHub in the classroom with a free Organization account" link on https://education.github.com/? 
![image](https://cloud.githubusercontent.com/assets/8030138/20856506/717f6dcc-b8de-11e6-915e-f87975ae670d.png)

If not, I can go through the link in the hope of getting a free upgrade.

**Comment by ronboger** [comment]
nah, i didn't. would be awesome if you did that

**Comment by ryerrabelli** [comment]
Did it. Confirmation page said they'd contact me.
