### ISSUE TITLE
Put A-Level Capital, SoGal Ventures, Proscia as Partners

### ISSUE THREAD

**Issue by errcHuang** [medhacks/SplashPage2k16#6]
A-Level: http://www.hultprizeat.com/assets/Org-13%5Csponsor_635815518437505634.jpg
SoGal: http://res.cloudinary.com/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/SoGal_Ventures_logo_pink_extralight_zhtsh8.png
Proscia: https://media.licdn.com/mpr/mpr/shrink_200_200/AAEAAQAAAAAAAAPDAAAAJDdhNmYzOTU0LTQ0MTUtNGFkOC1iNTk1LTRkODllYmMyYzlkYw.png

**Comment by ronboger** [comment]
a-level and sogal should be in our assets from last year too

**Comment by ronboger** [comment]
@dwesty do you have a better logo for proscia we can put up? wanted to surprise you with this - we're all for supporting our MedHacks alumni who are doing awesome things

**Comment by ronboger** [comment]
Put them as sponsors

**Comment by eburnette1** [comment]
did we ever get a new logo for proscia?
